Numpy

In [1]:
import numpy as np

In [3]:
big_list = list(range(100000))
big_array = np.arange(100000)

In [7]:
%timeit [x**2 for x in big_list]

10.1 ms ± 281 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
%timeit big_array ** 2

106 μs ± 1.43 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
### creating arrays

In [10]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [13]:
b = np.array([[1,2,3,4],[5,6,7,8]]) #2D array
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
a = np.array([0,0,0,0])
print(a)

[0 0 0 0]


In [15]:
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [18]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [19]:
print(np.eye(3))  #identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
rng = np.random.default_rng(seed=42)
print(rng.random((2,3)))

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [24]:
print(rng.integers(1,10,size=(3,3))) #uniform

[[7 7 7]
 [8 5 2]
 [8 5 5]]


In [25]:
print(rng.normal(loc=0,scale=1,size=5))

[ 0.77779194  0.0660307   1.12724121  0.46750934 -0.85929246]


In [26]:
### Array attributes and data types

In [28]:
M = np.array([[1,2,3],[4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
print(M.ndim)

2


In [30]:
print(M.shape)

(2, 3)


In [31]:
print(M.size)

6


In [32]:
print(M.dtype)

int64


In [35]:
ints=np.array([1,2,3],dtype=np.int32)

In [36]:
ints.dtype

dtype('int32')

In [38]:
floats = np.array([1,2,3],dtype=np.float64)
floats.dtype

dtype('float64')

In [39]:
#indexing and slicing

In [40]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
print(x[0])

10


In [42]:
print(x[5])

15


In [43]:
M = np.arange(1,13).reshape(3,4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
print(M[1,2])

7


In [45]:
M[0]
M[1]

array([5, 6, 7, 8])

In [46]:
print(M[0])

[1 2 3 4]


In [47]:
print(M[1])

[5 6 7 8]


In [48]:
print(M[:,1])

[ 2  6 10]


In [49]:
print(M[:,0])

[1 5 9]


In [50]:
## vector operation

In [51]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

In [52]:
print(a)
print(b)

[1 2 3 4]
[10 20 30 40]


In [53]:
print(a+b)

[11 22 33 44]


In [54]:
print(a*b)

[ 10  40  90 160]


In [55]:
# Broadcasting

In [56]:
a = np.array([1,2,3])
b = 10

In [57]:
print(a+b)

[11 12 13]


In [58]:
a = np.array([[1,2,3],
             [4,5,6]])
a.shape

(2, 3)

In [59]:
b = np.array([10,20,30])
b.shape

(3,)

In [60]:
print(a+b)

[[11 22 33]
 [14 25 36]]


In [61]:
a = np.array

In [62]:
b = np.array([10,20,30])
b.shape

(3,)